recipe: default.v1

language: en

pipeline:
  - name: MitieNLP
    model: "data/total_word_feature_extractor.dat"
  - name: MitieTokenizer
  - name: MitieFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 50
    constrain_similarities: yes
  - name: FallbackClassifier
    threshold: 0.5
  - name: DucklingEntityExtractor
    dimensions: ["credit-card-number", "time", "number"]
    url: "http://localhost:8000"  #docker run -p 8000:8000 rasa/duckling
  - name: RegexEntityExtractor
    # text will be processed with case insensitive as default
    case_sensitive: False
    # use lookup tables to extract entities
    use_lookup_tables: True
    # use regexes to extract entities
    use_regexes: True
    # use match word boundaries for lookup table
    use_word_boundaries: True
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50

policies:
  - name: TEDPolicy
    max_history: 7
    epochs: 50
    constrain_similarities: yes
  - name: AugmentedMemoizationPolicy
    max_history: 4
  - name: RulePolicy